# Generated by Django 4.2.6 on 2023-10-17 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_buku', models.PositiveIntegerField()),
                ('judul', models.CharField(max_length=255)),
                ('jumlah_halaman', models.PositiveIntegerField()),
                ('bahasa', models.CharField(max_length=50)),
                ('penulis', models.CharField(max_length=255)),
                ('penerbit', models.CharField(max_length=255)),
                ('jumlah_review', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gambar', models.ImageField(upload_to='book_covers/')),
                ('tanggal_terbit', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
