# Generated by Django 4.2.6 on 2023-10-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_buku_gambar_alter_buku_id_buku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='jumlah_review',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
