# Generated by Django 4.2.6 on 2023-10-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_buku_bahasa_alter_buku_judul_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='tanggal_terbit',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
