# Generated by Django 4.2.6 on 2023-10-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_buku_tanggal_terbit_alter_buku_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='gambar',
            field=models.ImageField(blank=True, default='default_profile_image', null=True, upload_to=''),
        ),
    ]
