# Generated by Django 4.2.6 on 2023-10-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_buku_is_published_buku_isi_buku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='is_published',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
