# Generated by Django 4.2.6 on 2023-10-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_buku_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='gambar',
            field=models.ImageField(upload_to=''),
        ),
    ]
