# Generated by Django 4.2.6 on 2023-10-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_buku_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='id_buku',
        ),
        migrations.AddField(
            model_name='buku',
            name='isi_buku',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
