# Generated by Django 4.2.5 on 2023-10-27 07:45

from django.db import migrations
from django.core.management import call_command


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "databuku.json")


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_buku_isi_buku_remove_buku_user_and_more'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
