# Generated by Django 4.2.5 on 2023-10-29 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_buku_gambar_alter_bukukreasi_gambar_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='buku_favorites',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
