# Generated by Django 4.2.6 on 2023-10-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_quotes_user_delete_profile'),
        ('main', '0008_buku_buku_favorites'),
    ]

    operations = [
    ]
