# Generated by Django 4.2.5 on 2023-11-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20231029_2311'),
        ('main', '0009_merge_20231029_2329'),
    ]

    operations = [
    ]
