# Generated by Django 5.0 on 2023-12-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='isi_buku',
            field=models.TextField(default='Sayangnya buku ini belum tersedia :(, silahkan coba buku lainnya'),
        ),
    ]
