# Generated by Django 4.2.6 on 2023-10-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_buku_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='is_published',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buku',
            name='isi_buku',
            field=models.TextField(blank=True, null=True),
        ),
    ]
