# Generated by Django 5.0 on 2023-12-07 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_buku_isi_buku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bukukreasi',
            name='buku_favorites',
            field=models.ManyToManyField(related_name='favorite_buku_kreasi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buku',
            name='buku_favorites',
            field=models.ManyToManyField(related_name='favorite_buku', to=settings.AUTH_USER_MODEL),
        ),
    ]
