# Generated by Django 4.2.7 on 2023-12-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_bukukreasi_buku_favorites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='isi_buku',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
