# Generated by Django 4.2.7 on 2023-12-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_buku_isi_buku_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukukreasi',
            name='isi_buku',
            field=models.TextField(blank='', help_text='Ceritakan Kisahmu...', null=''),
        ),
    ]
