# Generated by Django 4.1.3 on 2023-12-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20231129_1336'),
        ('main', '0016_alter_bukukreasi_isi_buku'),
    ]

    operations = [
    ]
