# Generated by Django 5.0 on 2023-12-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_buku_isi_buku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='isi_buku',
        ),
    ]
