# Generated by Django 4.2.6 on 2023-10-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul_baca', '0002_komentar_dari_buku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='tgl_komentar',
            field=models.DateField(auto_now_add=True),
        ),
    ]
