# Generated by Django 4.2.6 on 2023-10-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul_baca', '0004_alter_komentar_dari_buku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
