# Generated by Django 4.2.6 on 2023-10-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul_baca', '0005_alter_komentar_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='tgl_komentar',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
