# Generated by Django 4.1.3 on 2023-12-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul_baca', '0007_komentarkreasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='user',
            field=models.TextField(default='Anonymous'),
        ),
        migrations.AlterField(
            model_name='komentarkreasi',
            name='user',
            field=models.TextField(default='Anonymous'),
        ),
    ]
