# Generated by Django 4.1.3 on 2023-12-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul_baca', '0008_alter_komentar_user_alter_komentarkreasi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='user',
            field=models.TextField(verbose_name='Anonymous'),
        ),
        migrations.AlterField(
            model_name='komentarkreasi',
            name='user',
            field=models.TextField(verbose_name='Anonymous'),
        ),
    ]
