# Generated by Django 4.1.3 on 2023-12-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul_baca', '0009_alter_komentar_user_alter_komentarkreasi_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='komentarkreasi',
            name='user',
        ),
        migrations.AddField(
            model_name='komentar',
            name='nama',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='komentarkreasi',
            name='nama',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
