# Generated by Django 4.2.7 on 2023-12-10 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modul_baca', '0010_remove_komentar_user_remove_komentarkreasi_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentar',
            name='nama',
        ),
        migrations.AddField(
            model_name='komentar',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='KomentarKreasi',
        ),
    ]
