# Generated by Django 4.1.3 on 2023-12-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_merge_20231217_2219'),
        ('modul_baca', '0011_remove_komentar_nama_komentar_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentar',
            name='user',
        ),
        migrations.AddField(
            model_name='komentar',
            name='nama',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.CreateModel(
            name='KomentarKreasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Anonymous', max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('tgl_komentar', models.DateTimeField(auto_now_add=True)),
                ('isi_komentar', models.TextField()),
                ('dari_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='main.bukukreasi')),
            ],
        ),
    ]
